default: &default
  adapter: mysql2
  encoding: utf8
  username: akr
  password: akr
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: KFdev

test:
  <<: *default
  database: KFtest

production:
  <<: *default
  database: KFprod